services:

  api:
    build: .
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    environment:
      SKPR_LOCAL_ROUTER_LABEL: "skpr.host"
    volumes:
      - ./certificates:/mnt/certificates
      - /var/run/docker.sock:/var/run/docker.sock
